host_project_id      = "shared-vpc-internal-poc-tf"  # shared VPC host project (see environments/network-hub)
project_id          = "terraform-uat-internal-poc"
region              = "asia-south1"
environment         = "prod"
app_name            = "myapp"
compute_platform    = "gke"                # gke | cloud_run | compute_engine
container_image     = "asia-south1-docker.pkg.dev/my-gcp-project-prod/prod-myapp/app:latest"
authorized_ip_ranges = ["203.0.113.0/24"]
billing_account_id  = "012345-6789AB-CDEF01"
budget_amount        = 5000
notification_email  = "tushar16957@gmail.com"
