host_project_id      = "my-gcp-project-net-host"  # shared VPC host project (see environments/network-hub)
project_id          = "my-gcp-project-prod"
region              = "us-central1"
environment         = "prod"
app_name            = "myapp"
compute_platform    = "gke"                # gke | cloud_run | compute_engine
container_image     = "us-central1-docker.pkg.dev/my-gcp-project-prod/prod-myapp/app:latest"
authorized_ip_ranges = ["203.0.113.0/24"]
billing_account_id  = "012345-6789AB-CDEF01"
budget_amount        = 5000
notification_email  = "platform-team@example.com"
